"""
CSE644 Cloud Computing - Requirement 6
A simple Python web server, containerized with Docker, listening on port 8888.

Runs two ways:
  * In the container, gunicorn imports the module-level `app` object.
  * Locally for debugging:  python app.py
"""

import os
import platform
import socket
import time
from datetime import datetime, timezone

from flask import Flask, jsonify, render_template_string

# Port 8888 is mandated by the assignment. Kept configurable via env so the
# same image can be re-run on another port without a rebuild, but 8888 is the
# default and what the Dockerfile EXPOSEs.
PORT = int(os.environ.get("PORT", "8888"))

STARTED_AT = time.time()
STUDENT = os.environ.get("STUDENT", "Tray Branch")
COURSE = "CSE644 Cloud Computing"

app = Flask(__name__)

# Simple in-process counter. It intentionally resets when the container is
# recreated - that contrast is what makes the Requirement 8 volume demo
# meaningful (in-container state is ephemeral; volume state is not).
_request_count = 0


def _facts():
    """Runtime facts about the container this process is running inside."""
    return {
        "student": STUDENT,
        "course": COURSE,
        "requirement": 6,
        "hostname": socket.gethostname(),
        "container_ip": socket.gethostbyname(socket.gethostname()),
        "pid": os.getpid(),
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "listening_port": PORT,
        "uptime_seconds": round(time.time() - STARTED_AT, 1),
        "server_time_utc": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "requests_served": _request_count,
    }


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CSE644 &middot; Python Web Server on :{{ f.listening_port }}</title>
<style>
  :root {
    --bg:#0d1117; --panel:#161b22; --line:#30363d;
    --ink:#e6edf3; --dim:#8b949e; --accent:#58a6ff; --py:#ffd343;
  }
  * { box-sizing:border-box; }
  body {
    margin:0; min-height:100vh; background:var(--bg); color:var(--ink);
    font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
    display:flex; align-items:center; justify-content:center; padding:2rem;
  }
  .card {
    width:100%; max-width:680px; background:var(--panel);
    border:1px solid var(--line); border-radius:12px; overflow:hidden;
  }
  .bar { height:4px; background:linear-gradient(90deg,var(--py),var(--accent)); }
  .inner { padding:2.25rem; }
  .badge {
    display:inline-block; font:600 11px/1 ui-monospace,Menlo,Consolas,monospace;
    letter-spacing:.12em; text-transform:uppercase; color:var(--py);
    border:1px solid var(--py); border-radius:999px; padding:.45rem .7rem;
    margin-bottom:1.25rem;
  }
  h1 { margin:0 0 .4rem; font-size:1.85rem; letter-spacing:-.02em; }
  .sub { margin:0 0 1.75rem; color:var(--dim); }
  code { font-family:ui-monospace,Menlo,Consolas,monospace; color:var(--accent); }
  dl {
    margin:0; display:grid; grid-template-columns:auto 1fr; gap:.6rem 1.25rem;
    padding-top:1.5rem; border-top:1px solid var(--line);
    font:13px/1.5 ui-monospace,Menlo,Consolas,monospace;
  }
  dt { color:var(--dim); white-space:nowrap; }
  dd { margin:0; word-break:break-all; }
  footer {
    margin-top:1.75rem; padding-top:1.25rem; border-top:1px solid var(--line);
    color:var(--dim); font-size:13px;
  }
</style>
</head>
<body>
  <main class="card">
    <div class="bar"></div>
    <div class="inner">
      <span class="badge">Requirement 6 &middot; Python / Flask</span>
      <h1>Python Web Server in Docker</h1>
      <p class="sub">{{ f.course }} &middot; listening on port {{ f.listening_port }}</p>

      <p>
        This response was generated by a Flask application running under
        <code>gunicorn</code> inside a container built from
        <code>python:3.12-slim</code>. The values below are read live from the
        container at request time.
      </p>

      <dl>
        <dt>Student</dt>        <dd>{{ f.student }}</dd>
        <dt>Container host</dt> <dd>{{ f.hostname }}</dd>
        <dt>Container IP</dt>   <dd>{{ f.container_ip }}</dd>
        <dt>Worker PID</dt>     <dd>{{ f.pid }}</dd>
        <dt>Python</dt>         <dd>{{ f.python_version }}</dd>
        <dt>Listening on</dt>   <dd>0.0.0.0:{{ f.listening_port }}</dd>
        <dt>Uptime</dt>         <dd>{{ f.uptime_seconds }}s</dd>
        <dt>Server time</dt>    <dd>{{ f.server_time_utc }}</dd>
        <dt>Requests</dt>       <dd>{{ f.requests_served }}</dd>
      </dl>

      <footer>
        JSON view: <code>/api/info</code> &middot; Health: <code>/healthz</code>
      </footer>
    </div>
  </main>
</body>
</html>
"""


@app.after_request
def _count(response):
    global _request_count
    if not response.direct_passthrough:
        _request_count += 1
    return response


@app.get("/")
def index():
    return render_template_string(PAGE, f=_facts())


@app.get("/api/info")
def api_info():
    """Machine-readable view of the same facts - used by the evidence script."""
    return jsonify(_facts())


@app.get("/healthz")
def healthz():
    return "ok\n", 200, {"Content-Type": "text/plain"}


if __name__ == "__main__":
    # Local debugging path only. In the container gunicorn serves `app`.
    app.run(host="0.0.0.0", port=PORT)
